alter table customer_behaviour
rename to clean_customer_behaviour;
 --  The total revenue generated by male vs female -- 
select gender, sum(purchase_amount) from clean_customer_behaviour
group by gender;
 
-- which customer used a discount but still spent more than the average purchase --
SELECT customer_id, purchase_amount FROM clean_customer_behaviour
where discount_applied = "Yes" and purchase_amount >= (select avg(purchase_amount) from clean_customer_behaviour);

-- The top 5 products with the highest review rating --
select item_purchased, round(avg(review_rating),2) as average_review from clean_customer_behaviour
group by item_purchased
order by average_review desc
limit 5;

-- Comparing the average purchase amounts between standards and express shipping --
select shipping_type, avg(purchase_amount) from clean_customer_behaviour
where shipping_type in ("Express", "Standard")
group by shipping_type; 

-- Do suscribe customers spend more?  comparing average spend and total revenue between suscriber and non-suscriber --
select subscription_status, count(customer_id),round(avg(purchase_amount),2) as average_spend, sum(purchase_amount) as total_revenue from clean_customer_behaviour
group by subscription_status;

-- Top 5 products have the highest percentage of purchases with discounts applied -- 
select item_purchased, round(sum(case when discount_applied ='Yes' THEN 1 ELSE 0 END)/count(*),2) as discount_rate
from clean_customer_behaviour
group by item_purchased
order by discount_rate desc
limit 5;

-- Segment customers into new, returning and loyal. Based on their total number of previous purchase, and show the count of each segment --
WITH customer_type AS (
    SELECT 
        customer_id, 
        previous_purchases,
        CASE 
            WHEN previous_purchases = 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM clean_customer_behaviour
)
SELECT customer_segment, count(*) FROM customer_type
group by customer_segment;

-- What is the top 3 most purchased products within each category --
WITH item_counts AS (
    SELECT 
        category, item_purchased, COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM clean_customer_behaviour
    GROUP BY category, item_purchased)
SELECT item_rank, category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <= 3;

-- customer who are repeat buyers (more than 5 previous purchase) also likely to suscribe --
select subscription_status,count(customer_id) as repeat_buyers FROM clean_customer_behaviour
where previous_purchases>5 
group by subscription_status;

-- what is the revenue contribution of each age group --
select age_group, sum(purchase_amount) as revenue FROM clean_customer_behaviour
group by age_group
order by revenue Desc;